CREATE OR REPLACE TABLE `{{ YOUR_PROJECT }}.{{ YOUR_DATASET }}.communication_history_{{ YYYYMMDD }}_{{ SENDING_SYS_CD }}` (
	event_id STRING OPTIONS(description="a unique communication event id (PK), optional (mainly diagnostic / debugging / maintenance)")
	, event_type STRING NOT NULL OPTIONS(description="the type of event, is one of the following values: 'sent', 'bounce', 'open', 'click', ...")
	, event_category STRING NOT NULL OPTIONS(description="the category of event, is one of the following values: 'inbound', 'outbound', ...")
	, datetime TIMESTAMP OPTIONS(description="the timestamp of the event")
	, sending_id STRING NOT NULL OPTIONS(description="the id of the sending of the communication (unique per sending and per communication, but can have several events, like sent, open, click, the sending id must be generated by the channel as a unique identifier of each sent event...")
	, sending_sys_cd STRING NOT NULL  OPTIONS(description="the system code which sent the message (e.g.: 'NEWSLETTER', 'E-SHOP', ...)")
	, channel_id STRING OPTIONS(description="the id of the communication channel (optional)")
	, channel_name STRING NOT NULL OPTIONS(description="the channel (name) of the communication: 'email', ...")
	, run_id STRING OPTIONS(description="the id of the batch execution (can cover several sending ids) (optional)")
	, communication_id STRING NOT NULL OPTIONS(description="a unique communication id should be unique per message sent to a specific person and should match the communication_id of the communication_planning table")
	, message_id STRING NOT NULL OPTIONS(description="the id of the communication (unique per communication, but could be applied to many receipients, ...)")
	, message_name STRING OPTIONS(description="the name of the communication")
	, thread_id STRING OPTIONS(description="the id of the communication thread (should refer to a prior communication_id or message_id which is the root of the thread)")
	, thread_type STRING OPTIONS(description="the type of the communication thread (typically 'message' of 'communication', by default is is considered as a 'communication' thread)")
	, thread_name STRING OPTIONS(description="the name of the communication thread")
	, campaign_id STRING OPTIONS(description="the id of the campaign or communication group")
	, campaign_name STRING OPTIONS(description="the name of the campaign or communication group")
	, external_id STRING OPTIONS(description="an external id if provided by a separated system (for example, the request_id if provided by boxalino narrative response)")
	, receiver_id STRING OPTIONS(description="the persona_id as referenced in other tables")
	, receiver_type STRING OPTIONS(description="the type of persona (user, guest, ...)")
	, receiver_title STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, receiver_firstname STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, receiver_lastname STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, receiver_email STRING OPTIONS(description="the email address (can be null)")
	, receiver_visitor_ids ARRAY<STRING> OPTIONS(description="the visitor cookie ids from Boxalino of Google Analygtics (can be empty)")
	, receivers ARRAY<STRUCT<
		type STRING NOT NULL OPTIONS(description="e.g.: billing, shipping")
		, persona_id STRING OPTIONS(description="the persona_id as referenced in other tables")
		, persona_type STRING OPTIONS(description="the type of persona (user, guest, ...)")
		, internal_id STRING OPTIONS(description="an additional internal id (optional)")
		, external_id STRING OPTIONS(description="the external identifier of the user (can be the same as the internal identifier)")
		, title STRING
		, prefix STRING
		, firstname STRING
		, middlename STRING
		, lastname STRING
		, suffix STRING
		, gender STRING
		, date_of_birth DATETIME
		, account_creation DATETIME
		, creation_label STRING
		, auto_group STRING
		, invoice_status STRING
		, status STRING
		, spouse_id STRING
		, children_ids ARRAY<STRING NOT NULL>
		, customer_groups ARRAY<STRING NOT NULL>
		, stores ARRAY<STRING> OPTIONS(description="the stores")
		, websites ARRAY<STRING> OPTIONS(description="the stores")
		, company STRING
		, vat STRING
		, vat_is_valid BOOLEAN
		, vat_request_id STRING
		, vat_request_date DATETIME
		, vat_request_success BOOLEAN
		, street STRING
		, additional_address_line STRING
		, city STRING
		, zipcode STRING
		, stateID STRING
		, department STRING
		, statename STRING
		, countryiso STRING
		, countryID STRING
		, phone STRING
		, email STRING
		, mobile_phone STRING
		, fax STRING
		, giftregistry_item_id STRING
		, string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRING NOT NULL>>> OPTIONS(description="additional string (not localized) attributes of the voucher")
		, localized_string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>> OPTIONS(description="additional localized string attributes of the voucher")
		, numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<NUMERIC NOT NULL>>> OPTIONS(description="additional numeric (not localized) attributes of the voucher")
		, localized_numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<STRUCT<language STRING NOT NULL, value NUMERIC NOT NULL>>>> OPTIONS(description="additional localized numeric attributes of the voucher")
		, datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<DATETIME NOT NULL>>> OPTIONS(description="additional datetime (not localized) attributes of the voucher")
		, localized_datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>> OPTIONS(description="additional localized datetime attributes of the voucher")
		, subscriptions ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the subscriptions (e-mails and others)")
		, notifications ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the notofications (e-mails and others)")
		, voucher_states ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the vouchers (used and others)")
	>> OPTIONS(description="typically not use in case the receive is only 1 persona defined by its persona_id, but available for other cases")
	, receiver_attribute_1_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_1_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_2_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_2_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_3_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_3_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_4_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_4_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_5_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, receiver_attribute_5_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure receivers")
	, senders ARRAY<STRUCT<
		type STRING NOT NULL OPTIONS(description="e.g.: billing, shipping")
		, persona_id STRING OPTIONS(description="the persona_id as referenced in other tables")
		, persona_type STRING OPTIONS(description="the type of persona (user, guest, ...)")
		, internal_id STRING OPTIONS(description="an additional internal id (optional)")
		, external_id STRING OPTIONS(description="the external identifier of the user (can be the same as the internal identifier)")
		, title STRING
		, prefix STRING
		, firstname STRING
		, middlename STRING
		, lastname STRING
		, suffix STRING
		, gender STRING
		, date_of_birth DATETIME
		, account_creation DATETIME
		, creation_label STRING
		, auto_group STRING
		, invoice_status STRING
		, status STRING
		, spouse_id STRING
		, children_ids ARRAY<STRING NOT NULL>
		, customer_groups ARRAY<STRING NOT NULL>
		, stores ARRAY<STRING> OPTIONS(description="the stores")
		, websites ARRAY<STRING> OPTIONS(description="the stores")
		, company STRING
		, vat STRING
		, vat_is_valid BOOLEAN
		, vat_request_id STRING
		, vat_request_date DATETIME
		, vat_request_success BOOLEAN
		, street STRING
		, additional_address_line STRING
		, city STRING
		, zipcode STRING
		, stateID STRING
		, department STRING
		, statename STRING
		, countryiso STRING
		, countryID STRING
		, phone STRING
		, email STRING
		, mobile_phone STRING
		, fax STRING
		, giftregistry_item_id STRING
		, string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRING NOT NULL>>> OPTIONS(description="additional string (not localized) attributes of the voucher")
		, localized_string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>> OPTIONS(description="additional localized string attributes of the voucher")
		, numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<NUMERIC NOT NULL>>> OPTIONS(description="additional numeric (not localized) attributes of the voucher")
		, localized_numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<STRUCT<language STRING NOT NULL, value NUMERIC NOT NULL>>>> OPTIONS(description="additional localized numeric attributes of the voucher")
		, datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<DATETIME NOT NULL>>> OPTIONS(description="additional datetime (not localized) attributes of the voucher")
		, localized_datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>> OPTIONS(description="additional localized datetime attributes of the voucher")
		, subscriptions ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the subscriptions (e-mails and others)")
		, notifications ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the notofications (e-mails and others)")
		, voucher_states ARRAY<STRUCT<type STRING, name STRING NOT NULL, status INT64 NOT NULL, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="the state of the vouchers (used and others)")
	>> OPTIONS(description="information about the communication senders")
	, sender_id STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_type STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_title STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_firstname STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_lastname STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_email STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_1_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_1_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_2_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_2_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_3_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_3_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_4_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_4_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_5_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, sender_attribute_5_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure senders")
	, contents ARRAY<STRUCT<
		id STRING OPTIONS(description="the unique id of the content as provided in doc_content")
		, type STRING OPTIONS(description="the type of content as provided in doc_content: 'blog', 'magazin', 'page', ...")
		, language STRING OPTIONS(description="the language of the communication")
		, title STRING OPTIONS(description="the title of the content")
		, short_description STRING OPTIONS(description="the short description of the content")
		, description STRING OPTIONS(description="the description of the content")
		, parent_content_ids ARRAY<STRING NOT NULL>  OPTIONS(description="the parent contents related to this content (e.g.: rating of themost helpful customer review / comments)")
		, products ARRAY<STRUCT<type STRING, name STRING, product_line STRING, product_group STRING, sku STRING, value NUMERIC>> OPTIONS(description="connections to products")
		, contents ARRAY<STRUCT<type STRING, name STRING, content_type STRING, content_id STRING, value NUMERIC>> OPTIONS(description="relations to other contents")
		, topics ARRAY<STRUCT<name STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="the topics of the content")
		, brands ARRAY<STRUCT<name STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="the brands of the content")
		, suppliers ARRAY<STRUCT<name STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="the suppliers of the content")
		, categories ARRAY<STRUCT<categorization STRING NOT NULL, category_ids ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>> OPTIONS(description="the categories of the content")
		, images ARRAY<STRUCT<name STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="the images of the content")
		, link ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>> OPTIONS(description="the link of the content")
		, tags ARRAY<STRUCT<type STRING NOT NULL, value STRING NOT NULL, loc_values ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>> OPTIONS(description="the tags of the product line, e.g.: [STRUCT('tag', 'hello world', [STRUCT('de', 'hello world')])]")
		, labels ARRAY<STRUCT<type STRING NOT NULL, name STRING NOT NULL, value STRING NOT NULL, loc_values ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>> OPTIONS(description="the labels of the content, e.g.: [STRUCT('symbol', 'helpful', 'very', [STRUCT('de', 'sehr hilfreich')])]")
		, widgets ARRAY<STRING>  OPTIONS(description="widgets of the api request")
		, filters       ARRAY<STRUCT<key STRING NOT NULL, values ARRAY<STRING>>> OPTIONS(description="filters of the api request")
		, context_parameters       ARRAY<STRUCT<key STRING NOT NULL, values ARRAY<STRING>>> OPTIONS(description="parameters of the api request")
		, string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRING NOT NULL>>> OPTIONS(description="additional string (not localized) attributes of the content")
		, localized_string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="additional localized string attributes of the content")
		, numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<NUMERIC NOT NULL>>> OPTIONS(description="additional numeric (not localized) attributes of the content")
		, localized_numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value NUMERIC NOT NULL>>>>>> OPTIONS(description="additional localized numeric attributes of the content")
		, datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<DATETIME NOT NULL>>> OPTIONS(description="additional datetime (not localized) attributes of the content")
		, localized_datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="additional localized datetime attributes of the content")
	>>  OPTIONS(description="information about the content of the communication, typically only provided for the 'sent' event, as the other events should refer to the same message_id and persona_id / email so no need to indicate the content every time, only for sent")
	, content_id STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_id_field STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_language STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_title STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_short_description STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_description STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_1_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_1_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_2_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_2_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_3_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_3_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_4_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_4_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_5_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, content_attribute_5_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure contents")
	, string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRING NOT NULL>>> OPTIONS(description="additional string (not localized) attributes of the content")
	, localized_string_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>>>>>> OPTIONS(description="additional localized string attributes of the content")
	, numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<NUMERIC NOT NULL>>> OPTIONS(description="additional numeric (not localized) attributes of the content")
	, localized_numeric_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, key STRING, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value NUMERIC NOT NULL>>>>>> OPTIONS(description="additional localized numeric attributes of the content")
	, datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<DATETIME NOT NULL>>> OPTIONS(description="additional datetime (not localized) attributes of the content")
	, localized_datetime_attributes ARRAY<STRUCT<type STRING, name STRING NOT NULL, values ARRAY<STRUCT<value_id STRING, value ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>>>> OPTIONS(description="additional localized datetime attributes of the content")
	, attribute_1_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_1_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_2_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_2_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_3_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_3_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_4_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_4_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_5_name STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
	, attribute_5_value STRING  OPTIONS(description="use only if providing data in flat format (like CSV) if you skip the nested structure attributes")
    , creation_tm   DATETIME NOT NULL OPTIONS(description="technical field")
    , client_id     INT64 NOT NULL OPTIONS(description="technical field")
    , src_sys_id    INT64 NOT NULL OPTIONS(description="technical field")
) 
partition by date(datetime)
cluster by receiver_id
;