CREATE OR REPLACE TABLE `{{ YOUR_PROJECT }}.{{ YOUR_DATASET }}.doc_attribute_{{ F|D }}_{{ YYYYMMDD }}`  (
	  name STRING NOT NULL OPTIONS(description="the name of the attribute (should match the name of the attribute provided in the doc_product table in either string_attributes, numeric_attributes or localized_numeric_attributes")
	, internal_id STRING OPTIONS(description="the internal identifier of the attribute")
	, external_id STRING OPTIONS(description="the external identifier of the attribute (can be the same as the internal identifier)")
	, label ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>> OPTIONS(description="the title of the attribute")
	, attribute_group ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>> OPTIONS(description="the attribute group in which this attribute belongs")
	, attribute_sub_group ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>> OPTIONS(description="the attribute sub-group in which this attribute belongs")
	, stores ARRAY<STRING> OPTIONS(description="the stores")
	, format STRING NOT NULL OPTIONS(description="the type format of the attribute : 'numeric', 'string' or 'datetime', it is supported to set it to string but provide numeric attributes in the products, as lon as you have a mapping logic in the attribute values")
	, localized BOOLEAN NOT NULL OPTIONS(description="are the values localized (different for every language) or not, it is supported to set it to true but provide non-localized attributes in the products, as lon as you have a mapping logic in the attribute values")
	, link ARRAY<STRUCT<language STRING NOT NULL, value STRING NOT NULL>> OPTIONS(description="the link of the attribute value")
	, data_types ARRAY<STRING> OPTIONS(description="the list of related data types ('product', 'blog', 'content', ...), by default 'all' if empty")
	, multi_value BOOLEAN NOT NULL OPTIONS(description="is it possible for this attribute to have more than 1 value per sku (or final content), set to false unless necessary, as multi-valued vields cannot be sorted or grouped by")
	, hierarchical BOOLEAN NOT NULL OPTIONS(description="is it an attribute that has a hierarchy of values (e.g.: category tree)")
	, search_by INT64 NOT NULL OPTIONS(description="should be indexed as part of the searcheable : 0 : values not indexed for search, 1 : values indexed for search only in main index, 2 : values indexed for search in specialized field which can be boosted individually")
	, search_suggestion BOOLEAN NOT NULL OPTIONS(description="should this attribute values be used as search suggestions")
	, filter_by BOOLEAN NOT NULL OPTIONS(description="is it an attribute that needs to be used as a filter in some requests")
	, group_by BOOLEAN NOT NULL OPTIONS(description="is it a attribute that needs to be grouped by in some requests (if set to true, then multi_value must be set to false)")
	, order_by BOOLEAN NOT NULL OPTIONS(description="is it a attribute that needs to be ordered by in some requests (if set to true, then multi_value must be set to false)")
	, indexed BOOLEAN NOT NULL OPTIONS(description="should this attribute values be indexed independantly so they can be searched for (e.g.: author, brand, ...)")
	, visibility ARRAY<STRUCT<customer_groups ARRAY<STRING NOT NULL>, values ARRAY<STRUCT<language STRING NOT NULL, value INT64 NOT NULL>>>> OPTIONS(description="the product visibility :VISIBILITY_NOT_VISIBLE = 1; VISIBILITY_IN_CATALOG = 2; VISIBILITY_IN_SEARCH = 3; VISIBILITY_BOTH = 4;")
	, status ARRAY<STRUCT<language STRING NOT NULL, value INT64 NOT NULL>> OPTIONS(description="the product status")
	, periods ARRAY<STRUCT<start_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>, end_datetime ARRAY<STRUCT<language STRING NOT NULL, value DATETIME NOT NULL>>>> OPTIONS(description="information about the activity periods of the product group")
	, creation_tm   DATETIME NOT NULL OPTIONS(description="technical field")
    , client_id     INT64 NOT NULL OPTIONS(description="technical field")
    , src_sys_id    INT64 NOT NULL OPTIONS(description="technical field")
    )
OPTIONS(description="The attributes specifications");